name: Notify on Push or PR Merge

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Notify Event
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "🚀 Mainブランチにプッシュされました！"
            echo "コミットハッシュ: ${{ github.sha }}"
            echo "コミットメッセージ: ${{ github.event.head_commit.message }}"
            echo "プッシュしたユーザー: ${{ github.event.head_commit.author.name }}"
            echo "プッシュ時刻: ${{ github.event.head_commit.timestamp }}"
          else
            echo "🎉 プルリクエストがマージされました！"
            echo "PR番号: #${{ github.event.pull_request.number }}"
            echo "PRタイトル: ${{ github.event.pull_request.title }}"
            echo "マージしたユーザー: ${{ github.event.pull_request.merged_by.login }}"
            echo "マージ時刻: ${{ github.event.pull_request.merged_at }}"
            echo "ベースブランチ: ${{ github.event.pull_request.base.ref }}"
          fi